name: 'Checkout and Prepare Step'
description: 'Apply workarounds + Java Setup + Maven Repository Caching'
inputs:
  maven-cache-key:
    description: 'Cache key for maven repository'
    required: false
  maven-cache-restore-key:
    description: 'Cache restore key for maven repository'
    required: false
  maven-cache-path:
    description: 'Maven repository path to be cached'
    default: ~/.m2/repository
    required: false
  jacoco-cache-key:
    description: 'Cache key for jacoco and test execution data'
    required: false
  jacoco-cache-restore-key:
    description: 'Cache restore key for jacoco and test execution data'
    required: false
  java-version:
    description: 'Java version to setup'
    required: false
  repository_path:
    description: 'Path to clone the repository to, by default .'
    required: false
    default: .
  repository:
    desciption: 'Repository to clone, by default github.repository'
    required: false
    default: ${{ github.repository }}
  clone:
    description: 'Wheather to clone the repository as part of the composite action, defaulted to true'
    required: false
    default: true
  GPG_PRIVATE_KEY:
    required: false
  GPG_PASSPHRASE:
    required: false
  BUILD_USER:
    required: false
  BUILD_USER_PASSWD:
    required: false
  BUILD_USER_EMAIL:
    required: false
  GIT_TOKEN:
    description: 'GitHub actions token for repository cloning defaults to github.token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: "Use GNU tar instead BSD tar (Workaround https://github.com/actions/cache/issues/576#issuecomment-830796954)"
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
    
    - name: Enable git support for long paths on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: git config --system core.longpaths true
        
    - name: Restore m2 repository
      if: inputs.maven-cache-key != ''
      uses: actions/cache@v3
      with:
        path: ${{ inputs.maven-cache-path }}
        key: ${{ inputs.maven-cache-key }}
        restore-keys: ${{ inputs.maven-cache-restore-key }}
        enableCrossOsArchive: true
        
    - name: Restore jacoco test coverage data
      if: inputs.jacoco-cache-key != ''
      uses: actions/cache@v3
      with:
        path: |
          **/*.exec
          **/failsafe-reports/**/*
          **/surefire-reports/**/*
        key: ${{ inputs.jacoco-cache-key }}
        restore-keys: ${{ inputs.jacoco-cache-restore-key }}
        enableCrossOsArchive: true

    - name: Set up OpenJDK
      if: inputs.java-version != ''
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: adopt
    
    - name: Clone Repository
      if: inputs.clone == 'true'
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.repository_path }}
        token: ${{ inputs.git_token }}

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      if: inputs.GPG_PRIVATE_KEY != '' && inputs.GPG_PASSPHRASE != ''
      with:
        gpg_private_key: ${{ inputs.GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        workdir: ${{ inputs.repository_path }}
        
    - name: Setup git user
      if: inputs.BUILD_USER != '' && inputs.BUILD_USER_EMAIL != ''
      shell: bash
      run: |
        cd ${{ inputs.repository_path }}
        git config --global user.email ${{ inputs.BUILD_USER_EMAIL }}
        git config --global user.name ${{ inputs.BUILD_USER }}
        
    - name: Setup repo for push on protected branch
      if: inputs.BUILD_USER != '' && inputs.BUILD_USER_PASSWD != ''
      shell: bash
      run: |
        cd ${{ inputs.repository_path }}
        ORIGIN="$(git config --get remote.origin.url)"
        SED_OUT=$(echo $ORIGIN | sed -r -E -n 's@^https:\/\/(github.com.*)@\1@p')
        if [ -n "$SED_OUT" ]
        then
          ORIGIN="https://${{ inputs.BUILD_USER }}:${{ inputs.BUILD_USER_PASSWD }}@$SED_OUT"
          git remote set-url origin $ORIGIN
          echo "Changed remote URL to enable pushing on protected branch"
        fi
